extends Control

## 主菜单界面控制器
## 显示用户信息并提供退出登录功能

@onready var welcomeLabel: Label = $centerContainer/vboxContainer/welcomeLabel
@onready var userInfoLabel: Label = $centerContainer/vboxContainer/userInfoLabel
@onready var logoutButton: Button = $centerContainer/vboxContainer/logoutButton

func _ready():
	# 连接退出登录按钮
	logoutButton.pressed.connect(_onLogoutPressed)

	# 连接 AuthManager 信号
	AuthManager.logout_success.connect(_onLogoutSuccess)

	# 显示用户信息
	_displayUserInfo()

## 显示用户信息
func _displayUserInfo() -> void:
	var currentUser = AuthManager.getCurrentUser()

	if currentUser != null:
		userInfoLabel.text = "用户名：%s\n等级：%d" % [currentUser.username, currentUser.level]
	else:
		userInfoLabel.text = "未登录"

## 退出登录按钮点击事件
func _onLogoutPressed() -> void:
	# 调用 AuthManager 登出
	AuthManager.logout()

## 登出成功回调
func _onLogoutSuccess() -> void:
	# 返回登录界面
	get_tree().change_scene_to_file("res://scenes/login_scene.tscn")
